name: ecopulse
description: EcoPulse client (Windows/Mobile)
version: 1.0.3+1
license: MIT

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10
  flutter_riverpod: ^2.5.1
  flutter_launcher_icons: ^0.13.1
  dio: ^5.5.0
  cupertino_icons: ^1.0.8
  socket_io_client: ^2.0.3
  shared_preferences: ^2.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/app_icon.svg
    - lib/assets/EULA.txt

flutter_launcher_icons:
  android: true
  ios: true

  image_path: "lib/assets/app_icon_1024.png"

  adaptive_icon_foreground: "lib/assets/app_icon_1024.png"
  adaptive_icon_background: "#FFFFFF"
  remove_alpha_ios: true
