name: ecopulse
description: EcoPulse client (Windows)
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  dio: ^5.5.0
  cupertino_icons: ^1.0.8
  socket_io_client: ^2.0.3
  shared_preferences: ^2.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
